# The playbook currently runs an echo command to print a fruit name. Apply a loop directive (with_items) to the task to print all fruits defined in the "fruits" variable.
# WA. note this.. it is the first time you see this structure: fruits is a list defined at the play level! It is not a variable defined with 'vars' directive, but yet used
# as a variable in the task
# ------------------------------
#           BEFORE
# ------------------------------
#  name: Print list of fruits
#-
#  hosts: localhost
#  fruits:
#    - Apple
#    - Banana
#    - Grapes
#    - Orange
#  tasks:
#    -
#      command: echo "Apple"#
# ------------------------------
#           AFTER
# ------------------------------
-
  name: Print list of fruits
  hosts: localhost
  fruits:
    - Apple
    - Banana
    - Grapes
    - Orange
  tasks:
    -
      command: echo "{{ item }}"
      with_items: '{{ fruits }}'


